name: Nascent
favicon: null
layout_spectrum: 0.75906
typography_spectrum: 0.42301578680053353
title: Nascent Concept Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030202'
    - '#595959'
    - '#afcaa3'
    - '#6fa697'
  brandStrength: 0.9172187962103635
  lightness: 0.3371292215306312
  saturation: 0.6645181595813483
  rhythmicContrast: 0.117985007353127
purpose: []
